package Exponential;


/**
* Exponential/ExpoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./com/year3/distributedsystem/lecture4/corba/exponential/Expo.idl
* Friday, April 1, 2022 8:22:04 PM ICT
*/

public interface ExpoOperations 
{
  int calculate (int a, int b);
} // interface ExpoOperations
