package Counter;


/**
* Counter/Count.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./com/year3/distributedsystem/lecture4/corba/Count.idl
* Friday, April 1, 2022 8:00:24 PM ICT
*/

public interface Count extends CountOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Count
