package Counter;


/**
* Counter/CountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./com/year3/distributedsystem/lecture4/corba/Count.idl
* Friday, April 1, 2022 8:00:24 PM ICT
*/

public interface CountOperations 
{
  int sum ();
  void sum (int newSum);
  int increment ();
} // interface CountOperations
